"""The ``!control-status`` instrument: a front panel of plain wires.

One instance is one entity behind one APB port, holding the two halves of
``gatecap.control_status`` and the crossings between them: the register shell
on the host clock, where controls are stored and read back, and the event core
on the panel's own clock, where ticks are strobed, stickies latched and
counters run. The split is what makes the panel survive a host clock that only
runs while a probe drives it.

The description says what wires there are; everything else follows. Each
control and status becomes one register of the declared width and one boundary
port, each tick one bit of a packed word and one boundary port, and the four
kinds together decide the map behind the APB port -- which is fixed by the
register-map convention, so the footprint is the same 0x400 bytes for every
panel.

The instance name prefixes every boundary port, and the entity the plugin
emits is named after the rack and the instance, so the backplane binds it
formal to formal.
"""

from __future__ import annotations

from acrobe_plugin.gatecap.generator import (Architecture, Assignment, Check,
                                             ClockDomain, Constant, DesignFile,
                                             Entity, Expr, Generic, Instance,
                                             InstrumentPlugin,
                                             InstrumentRegistry, Port,
                                             SignalDecl)
from .cdc import PanelCdc
from .parser import BodyParser


class Panel:
    """One elaborated instance: its ports, its two halves, the crossings
    between them and the descriptor envelope that publishes the lot."""

    ARCHITECTURE = "rtl"
    HEADER = ("Control/status panel generated by acrobe gatecap generate.\n"
              "Regenerate from the description; edits here are lost.")
    CLOCK = "clock_i"
    RESET_N = "reset_n_i"
    APB_CONFIG = "apb_config_c"
    SIZE_L2 = "size_l2_c"
    FINGERPRINT = "fingerprint_c"
    MAP_SIZE_L2 = "map_size_l2_c"
    # Bytes of address space the four register regions span, log2. Every panel
    # has the same footprint: the map is the register-map convention itself.
    FOOTPRINT_L2 = 10
    COUNTER_WIDTH = "counter_width_c"
    COUNTER_COUNT = "counter_count_c"
    SHELL = "gatecap.control_status.control_status_shell"
    CORE = "gatecap.control_status.control_status_core"
    ENVELOPE = "control_status_envelope"
    BLOCK_OBJECT = "control_status_block_desc"
    CHILD_MAP = "child_map"
    CHILD_ENTRY = "sibling_entry"
    # The one child of the envelope: the register block, at offset 0.
    BLOCK = "registers"
    HOST = "host"
    PANEL = "panel"
    DEPS = ("gatecap.control_status", "gatecap.descriptor", "nsl_amba.apb",
            "nsl_math.int_ext", "nsl_synthesis.assertion")
    USES = ("gatecap.control_status.all",)

    # Kind -> the generic of the library entities that dimensions it.
    CONTROL_WIDTH = "control_width_c"
    STATUS_WIDTH = "status_width_c"
    TICK_OUT_COUNT = "tick_out_count_c"
    TICK_IN_COUNT = "tick_in_count_c"

    def __init__(self, instrument, host_clock=None):
        self.instrument = instrument
        self.body = instrument.params["panel"]
        self.host = ClockDomain(self.HOST, self.CLOCK, self.RESET_N)
        self.core_clock = self.__core_domain(host_clock)
        self.down = PanelCdc(self.host, self.core_clock)
        self.up = PanelCdc(self.core_clock, self.host)
        self.tick_out_strobe = self.down.tick(
            self.signal("core_tick_out_strobe"),
            self.signal("shell_tick_out_strobe"))
        self.sticky_clear_strobe = self.down.tick(
            self.signal("core_sticky_clear_strobe"),
            self.signal("shell_sticky_clear_strobe"))
        self.__crossings()

    def __core_domain(self, host_clock):
        """The clock the event core runs on.

        A panel with no declared clock runs on the host clock, ports and all.
        One whose declared clock is the very clock the rack was told to ride
        keeps its clock port -- that port is where the rack takes the clock
        from -- and reads it back on the entity's own clock input, so the two
        are one domain and every crossing collapses."""
        if self.body.clock is None:
            return self.host
        own = self.body.clock != host_clock
        return ClockDomain(self.PANEL,
                           self.clock_port() if own else self.CLOCK,
                           self.reset_port())

    # Names

    def name(self, suffix):
        return f"{self.instrument.name}_{suffix}"

    @staticmethod
    def signal(stem):
        return f"{stem}_s"

    def clock_port(self):
        return self.name(f"{self.body.clock}_i")

    def reset_port(self):
        return self.name("reset_n_i")

    def entity_name(self, rack_entity):
        return f"{rack_entity}_{self.instrument.name}"

    # Boundary

    def ports(self):
        """What the instance puts on the rack boundary, and what the entity
        takes under the same names: the panel's clock and reset when it has
        one, then one port per signal, sliced to its declared width."""
        ports = []
        if self.body.clock is not None:
            ports.append(Port(self.clock_port(), "in", "std_ulogic"))
            ports.append(Port(self.reset_port(), "in", "std_ulogic"))
        for level in self.body.controls:
            ports.append(Port(self.name(f"{level.name}_o"), "out",
                              level.port_type()))
        for level in self.body.statuses:
            ports.append(Port(self.name(f"{level.name}_i"), "in",
                              level.port_type()))
        for word in self.body.tick_out:
            for tick in word.names:
                ports.append(Port(self.name(f"{tick}_o"), "out", "std_ulogic"))
        for word in self.body.tick_in:
            for tick in word.names:
                ports.append(Port(self.name(f"{tick}_i"), "in", "std_ulogic"))
        return tuple(ports)

    def exported_clocks(self):
        """The panel's own clock, under the name the description gave it."""
        if self.body.clock is None:
            return {}
        return {self.body.clock: self.clock_port()}

    # Geometry

    @staticmethod
    def widths(values):
        """A boundary generic: the widths position-wise, ascending. A kind
        with no signal at all is the library's empty vector."""
        if not values:
            return "no_panel_signals_c"
        return "(" + ", ".join(f"{index} => {value}"
                               for index, value in enumerate(values)) + ")"

    def constants(self):
        body = self.body
        return [
            Constant(self.MAP_SIZE_L2, "natural", str(self.FOOTPRINT_L2),
                     comment="Bytes of address space the register map spans, "
                             "log2: the four regions of the register-map "
                             "convention, one word per register."),
            Constant(self.CONTROL_WIDTH, "nsl_math.int_ext.integer_vector",
                     self.widths([level.width for level in body.controls]),
                     comment="Declared width of each control, in description "
                             "order, which is register order."),
            Constant(self.STATUS_WIDTH, "nsl_math.int_ext.integer_vector",
                     self.widths([level.width for level in body.statuses])),
            Constant(self.TICK_OUT_COUNT, "nsl_math.int_ext.integer_vector",
                     self.widths([word.count() for word in body.tick_out]),
                     comment="Ticks packed in each tick-out word: one word is "
                             "one simultaneity group."),
            Constant(self.TICK_IN_COUNT, "nsl_math.int_ext.integer_vector",
                     self.widths([word.count() for word in body.tick_in])),
            Constant(self.COUNTER_WIDTH, "natural",
                     str(body.counter_width),
                     comment="Width of every tick-input counter. Counters "
                             "wrap at it, and only that many bits cross."),
            Constant(self.COUNTER_COUNT, "natural",
                     Expr.call("panel_bit_total", self.TICK_IN_COUNT),
                     comment="One counter per tick input, word-major: the "
                             "library counts them from the very generic the "
                             "core is given."),
            ]

    def checks(self):
        return [
            Check("footprint_check",
                  "the declared footprint must match the map the panel "
                  "decodes",
                  f"{self.SIZE_L2} = {self.MAP_SIZE_L2}"),
            Check("address_width_check",
                  "the APB configuration must cover the panel's footprint",
                  f"{self.APB_CONFIG}.address_width >= {self.MAP_SIZE_L2}"),
            ]

    # Structure

    def word_vector(self, count):
        return f"panel_word_vector(0 to {count-1})"

    def signals(self):
        body = self.body
        controls = self.word_vector(len(body.controls))
        statuses = self.word_vector(len(body.statuses))
        tick_out = self.word_vector(len(body.tick_out))
        tick_in = self.word_vector(len(body.tick_in))
        counters = f"panel_word_vector(0 to {self.COUNTER_COUNT}-1)"
        return [
            SignalDecl(self.signal("shell_control"), controls),
            SignalDecl(self.signal("core_control"), controls,
                       comment="Controls never reach the core: they are "
                               "stored in the shell and cross straight to the "
                               "user ports."),
            SignalDecl(self.signal("core_status_in"), statuses),
            SignalDecl(self.signal("core_status_out"), statuses),
            SignalDecl(self.signal("shell_status"), statuses),
            SignalDecl(self.signal("shell_tick_out_mask"), tick_out),
            SignalDecl(self.signal("core_tick_out_mask"), tick_out),
            SignalDecl(self.signal("shell_tick_out_strobe"), "std_ulogic"),
            SignalDecl(self.signal("core_tick_out"), tick_out),
            SignalDecl(self.signal("core_tick_in"), tick_in),
            SignalDecl(self.signal("shell_sticky_clear"), tick_in),
            SignalDecl(self.signal("core_sticky_clear"), tick_in),
            SignalDecl(self.signal("shell_sticky_clear_strobe"), "std_ulogic"),
            SignalDecl(self.signal("core_sticky"), tick_in),
            SignalDecl(self.signal("shell_sticky"), tick_in),
            SignalDecl(self.signal("core_counter"), counters),
            SignalDecl(self.signal("shell_counter"), counters),
            ]

    def __crossings(self):
        """The inner contract, crossed: one primitive per word, in the
        direction the word travels."""
        body = self.body
        self.down.words("control", self.signal("shell_control"),
                        self.signal("core_control"), len(body.controls))
        self.up.words("status", self.signal("core_status_out"),
                      self.signal("shell_status"), len(body.statuses))
        self.down.static_words("tick_out_mask",
                               self.signal("shell_tick_out_mask"),
                               self.signal("core_tick_out_mask"),
                               len(body.tick_out))
        self.down.static_words("sticky_clear",
                               self.signal("shell_sticky_clear"),
                               self.signal("core_sticky_clear"),
                               len(body.tick_in))
        self.up.words("sticky", self.signal("core_sticky"),
                      self.signal("shell_sticky"), len(body.tick_in))
        self.up.counters("counter", self.signal("core_counter"),
                         self.signal("shell_counter"), body.counter_count(),
                         self.COUNTER_WIDTH)

    def shell(self):
        return Instance(
            "shell", self.SHELL,
            generic_map={
                "apb_config_c": self.APB_CONFIG,
                self.CONTROL_WIDTH: self.CONTROL_WIDTH,
                self.STATUS_WIDTH: self.STATUS_WIDTH,
                self.TICK_OUT_COUNT: self.TICK_OUT_COUNT,
                self.TICK_IN_COUNT: self.TICK_IN_COUNT,
                "tick_counter_width_c": self.COUNTER_WIDTH,
                "fingerprint_c": self.FINGERPRINT,
                },
            port_map={
                "clock_i": self.host.clock,
                "reset_n_i": self.host.reset_n,
                "apb_i": "apb_i",
                "apb_o": "apb_o",
                "control_o": self.signal("shell_control"),
                "status_i": self.signal("shell_status"),
                "tick_out_mask_o": self.signal("shell_tick_out_mask"),
                "tick_out_strobe_o": self.signal("shell_tick_out_strobe"),
                "sticky_clear_o": self.signal("shell_sticky_clear"),
                "sticky_clear_strobe_o":
                    self.signal("shell_sticky_clear_strobe"),
                "sticky_i": self.signal("shell_sticky"),
                "counter_i": self.signal("shell_counter"),
                },
            comment="The register file, on the host clock. It holds the "
                    "controls and the counter bases and never needs its clock "
                    "to run between accesses.")

    def core(self):
        return Instance(
            "core", self.CORE,
            generic_map={
                self.STATUS_WIDTH: self.STATUS_WIDTH,
                self.TICK_OUT_COUNT: self.TICK_OUT_COUNT,
                self.TICK_IN_COUNT: self.TICK_IN_COUNT,
                "tick_counter_width_c": self.COUNTER_WIDTH,
                },
            port_map={
                "clock_i": self.core_clock.clock,
                "reset_n_i": self.core_clock.reset_n,
                "status_i": self.signal("core_status_in"),
                "status_o": self.signal("core_status_out"),
                "tick_out_mask_i": self.signal("core_tick_out_mask"),
                "tick_out_strobe_i": self.tick_out_strobe,
                "tick_out_o": self.signal("core_tick_out"),
                "tick_in_i": self.signal("core_tick_in"),
                "sticky_clear_i": self.signal("core_sticky_clear"),
                "sticky_clear_strobe_i": self.sticky_clear_strobe,
                "sticky_o": self.signal("core_sticky"),
                "counter_o": self.signal("core_counter"),
                },
            comment="The event logic, on the panel's clock. Nothing here may "
                    "miss an event, so it runs on a clock the user keeps "
                    "permanent.")

    def boundary(self):
        """The user ports, sliced to their declared widths: unused high bits
        of an output are driven low, unused high bits of an input ignored."""
        statements = []
        for index, level in enumerate(self.body.controls):
            word = f"{self.signal('core_control')}({index})"
            value = f"{word}(0)" if level.scalar() \
                else f"unsigned({word}({level.width-1} downto 0))"
            statements.append(Assignment(self.name(f"{level.name}_o"), value))
        for index, level in enumerate(self.body.statuses):
            port = self.name(f"{level.name}_i")
            value = f"unsigned'(0 => {port})" if level.scalar() else port
            statements.append(Assignment(
                f"{self.signal('core_status_in')}({index})",
                Expr.call("panel_masked", value, str(level.width))))
        for index, word in enumerate(self.body.tick_out):
            for bit, tick in enumerate(word.names):
                statements.append(Assignment(
                    self.name(f"{tick}_o"),
                    f"{self.signal('core_tick_out')}({index})({bit})"))
        for index, word in enumerate(self.body.tick_in):
            statements.append(Assignment(
                f"{self.signal('core_tick_in')}({index})",
                self.__tick_in_word(word)))
        return statements

    def __tick_in_word(self, word):
        parts = [f"{bit} => {self.name(f'{tick}_i')}"
                 for bit, tick in enumerate(word.names)]
        if word.count() < 32:
            parts.append("others => '0'")
        return "(" + ", ".join(parts) + ")"

    # Entity

    def entity(self, rack_entity):
        return Entity(
            self.entity_name(rack_entity),
            (Generic(self.APB_CONFIG, "nsl_amba.apb.config_t",
                     comment="Completer geometry of the rack this panel sits "
                             "in. Only its low bits are decoded here."),
             Generic(self.SIZE_L2, "natural",
                     comment="Address-space footprint the envelope declares, "
                             "log2. The map below is fixed by the register-map "
                             "convention and asserted equal to it."),
             Generic(self.FINGERPRINT, "unsigned(31 downto 0)",
                     comment="Per-instance UID of the rack's descriptor, "
                             "which the register file reports.")),
            (Port(self.CLOCK, "in", "std_ulogic"),
             Port(self.RESET_N, "in", "std_ulogic"),
             Port("apb_i", "in", "nsl_amba.apb.master_t"),
             Port("apb_o", "out", "nsl_amba.apb.slave_t"))
            + self.ports(),
            comment=self.__entity_comment())

    def __entity_comment(self):
        body = self.body
        lines = [f"Control/status panel {self.instrument.name}: "
                 f"{len(body.controls)} control(s), {len(body.statuses)} "
                 f"status(es), {sum(w.count() for w in body.tick_out)} tick "
                 f"output(s) and {body.counter_count()} tick input(s).",
                 "",
                 "One APB completer holds the whole panel: the action, "
                 "config, status and array regions of the register-map "
                 "convention, one word per register."]
        if body.clock is None:
            lines += ["",
                      "The panel names no clock of its own, so shell and core "
                      "are one domain and every crossing of the inner "
                      "contract is a plain wire."]
        else:
            lines += ["",
                      "The register shell runs on the rack's clock and the "
                      "event core on the panel's own, which the user must "
                      "keep permanent: the host clock may stop between "
                      "accesses, and no event may be missed."]
        return "\n".join(lines)

    def declarations(self):
        return tuple(self.constants() + self.signals()
                     + self.up.declarations + self.down.declarations)

    def statements(self):
        statements = []
        for check in self.checks():
            statements += list(check.statements())
        statements += [self.shell(), self.core()]
        statements += self.down.statements + self.up.statements
        statements += self.boundary()
        return tuple(statements)

    def architecture(self, rack_entity):
        return Architecture(self.ARCHITECTURE, self.entity_name(rack_entity),
                            self.declarations(), self.statements())

    def file(self, rack_entity):
        return DesignFile(
            header=self.HEADER,
            clauses=DesignFile.context(
                DesignFile.libraries_of(sorted(set(self.deps()))), self.USES),
            units=(self.entity(rack_entity),
                   self.architecture(rack_entity))).render()

    # Descriptor

    def envelope(self):
        body = self.body
        return Expr.wrapped_call(
            self.ENVELOPE,
            size_l2=str(self.FOOTPRINT_L2),
            name=Expr.string(self.instrument.name),
            children=self.children(),
            control_names=Expr.string(body.spec_of(body.controls)),
            status_names=Expr.string(body.spec_of(body.statuses)),
            tick_out_names=Expr.string(body.group_spec_of(body.tick_out)),
            tick_in_names=Expr.string(body.group_spec_of(body.tick_in)),
            counter_width=str(body.counter_width))

    def children(self):
        entry = Expr.wrapped_call(self.CHILD_ENTRY, Expr.string(self.BLOCK),
                                  "0", Expr.maybe_call(self.BLOCK_OBJECT))
        return f"{self.CHILD_MAP}(\n{Expr.indent(entry)})"

    # Dependencies

    def deps(self):
        return tuple(list(self.DEPS) + list(self.down.deps())
                     + list(self.up.deps()))


@InstrumentRegistry.register
class ControlStatus(InstrumentPlugin):
    """A generic front panel: plain wires read, written and strobed from the
    host, with no capture around them."""

    TAG = "!control-status"
    KEYS = BodyParser.KEYS

    @classmethod
    def parse(cls, payload, path):
        return BodyParser.parse(payload, path)

    @classmethod
    def panel(cls, instrument, host_clock=None):
        return Panel(instrument, host_clock)

    @classmethod
    def contributed(cls, context):
        return Panel(context.instrument, context.host_clock)

    @classmethod
    def ports(cls, instrument):
        return cls.panel(instrument).ports()

    @classmethod
    def clocks(cls, instrument):
        return cls.panel(instrument).exported_clocks()

    @classmethod
    def envelope(cls, context):
        return cls.contributed(context).envelope()

    @classmethod
    def components(cls, context):
        panel = cls.contributed(context)
        return (panel.entity(context.entity).component(),)

    @classmethod
    def instance(cls, context):
        panel = cls.contributed(context)
        port_map = {Panel.CLOCK: context.clock,
                    Panel.RESET_N: context.reset_n,
                    "apb_i": context.apb_master,
                    "apb_o": context.apb_slave}
        for port in panel.ports():
            port_map[port.name] = port.name
        return Instance(
            context.instrument.label("panel"),
            panel.entity_name(context.entity),
            generic_map={Panel.APB_CONFIG: context.apb_config,
                         Panel.SIZE_L2: context.size_l2,
                         Panel.FINGERPRINT: context.fingerprint},
            port_map=port_map,
            comment=f"Control/status panel {context.instrument.name}. Every "
                    "port crosses untouched, the panel's clock included: a "
                    "clock re-driven through a signal assignment would gain a "
                    "delta cycle and skew its domain.")

    @classmethod
    def files(cls, context):
        panel = cls.contributed(context)
        name = panel.entity_name(context.entity)
        return {f"{name}.vhd": panel.file(context.entity)}

    @classmethod
    def deps(cls, instrument):
        return cls.panel(instrument).deps()
