"""Rack assembly: a description into a VHDL rack.

Three design units come out of it, plus whatever the instruments emit. A
package carries everything both entities have to agree on -- the word width,
the descriptor ROM's segment, one envelope function per instrument, the
envelope concatenation allocation walks, the composed descriptor and the
default APB configuration. A backplane entity holds the descriptor ROM, the
prefix router and the instruments, on APB alone. A rack entity holds the
communication adapter -- a gatecap library entity, selected by the
description's transport mode -- and instantiates the backplane behind it.

Two entities cannot share an elaboration constant through an instantiation --
a generic flows down, never up -- so the package is the single source of truth
by construction: both entities call the same functions on the same generics.
The envelopes are functions rather than constants because an instrument
dimensioned by a generic (a probe whose width only the instantiating design
knows) has no footprint until the entity elaborates, and a VHDL-93 package
takes no generics.

Emission is deterministic. Order follows the description everywhere it can and
a fixed rule everywhere else, and nothing carries a timestamp, so regenerating
an unchanged description rewrites identical files.
"""

from __future__ import annotations

import os

from .checks import Check
from .communication import CommunicationContext, HostClock
from .errors import DescriptionError
from .gbs import GbsManifest
from .instruments import InstrumentContext
from .vhdl import (Architecture, Constant, DesignFile, Entity, Expr,
                   FunctionBody, FunctionDecl, Generic, Instance, Package,
                   PackageBody, Port, RawStatement, SignalDecl)


class RackAssembly:
    """One generated rack: its package, its backplane and its rack entity."""

    HEADER = ("Rack generated by acrobe gatecap generate.\n"
              "Regenerate from the description; edits here are lost.")
    ARCHITECTURE = "rtl"
    BACKPLANE_SUFFIX = "_backplane"
    # Bytes per APB word, log2. Every register file in a rack is 32 bits wide.
    DATA_BUS_WIDTH_L2 = 2
    # The descriptor ROM's segment: the smallest one worth allocating, pinned
    # at address 0.
    ROM_SIZE_L2 = 12
    # The ROM is pinned, so this is what every adapter publishes as the
    # descriptor's byte address.
    DESCRIPTOR_BASE = "0"
    # Address bits the rack provisions when nothing wider is asked for.
    ADDRESS_WIDTH = 24
    # nsl_amba.address.routing_table holds sixteen entries, and the descriptor
    # ROM takes the first.
    MAX_INSTRUMENTS = 15

    DISPATCH = "nsl_amba.apb_routing.apb_dispatch"
    ROM = "nsl_amba.rom.apb_rom"
    ROM_IMPLEMENTATION = "nsl_memory.rom.ROM_DISTRIBUTED"

    DATA_BUS_WIDTH = "data_bus_width_l2_c"
    ROM_SIZE = "rom_size_l2_c"
    ENVELOPES = "envelopes_c"
    BASES = "segment_base_c"
    ADDRESS_BITS = "address_bits_c"
    DESCRIPTOR = "descriptor_c"
    FINGERPRINT = "fingerprint_c"
    ALLOCATION = "allocation_c"
    ROUTING_TABLE = "routing_table_c"
    APB_CONFIG = "apb_config_c"
    APB_TYPE = "nsl_amba.apb.config_t"
    APB_MASTER = "apb_m_s"
    APB_SLAVE = "apb_s_s"
    DOUT = "dout_s"
    DIN = "din_s"
    # The backplane's own clock and reset ports. What the rack binds them to
    # is the rack's business: its own ports, or a clock an instrument exports.
    CLOCK = "clock_i"
    RESET_N = "reset_n_i"

    PACKAGE_USES = ("gatecap.descriptor.all", "nsl_data.bytestream.all")
    DEPS = ("gatecap.descriptor", "nsl_amba.address", "nsl_amba.apb",
            "nsl_amba.apb_routing", "nsl_amba.rom", "nsl_data.bytestream",
            "nsl_math.arith", "nsl_memory.rom", "nsl_synthesis.assertion")

    def __init__(self, description):
        self.description = description
        if len(description.instruments) > self.MAX_INSTRUMENTS:
            raise DescriptionError(
                f"{len(description.instruments)} instruments need one APB "
                f"segment each, the router holds {self.MAX_INSTRUMENTS} "
                "beside the descriptor ROM", "instruments")
        self.clocks = HostClock.resolve(description)
        self.instruments = {}
        for index, instrument in enumerate(description.instruments):
            self.instruments[instrument.name] = instrument.plugin.contribute(
                InstrumentContext(
                    instrument=instrument,
                    clock=self.CLOCK,
                    reset_n=self.RESET_N,
                    apb_config=self.APB_CONFIG,
                    apb_master=Expr.index(self.DOUT, index + 1),
                    apb_slave=Expr.index(self.DIN, index + 1),
                    data_bus_width_l2=self.DATA_BUS_WIDTH,
                    fingerprint=self.FINGERPRINT,
                    clock_frequency=self.clocks.frequency,
                    entity=description.name.entity,
                    host_clock=self.host_clock(instrument),
                    size_l2=Expr.call(
                        "envelope_size_l2",
                        Expr.call("envelope_nth", self.ENVELOPES, index))))
        self.communication = description.communication.plugin
        self.communication_context = CommunicationContext(
            clock=self.clocks.clock,
            reset_n=self.clocks.reset_n,
            apb_config=self.APB_CONFIG,
            apb_master=self.APB_MASTER,
            apb_slave=self.APB_SLAVE,
            descriptor_base=self.DESCRIPTOR_BASE,
            clock_frequency=self.clocks.frequency,
            fingerprint=Expr.call("descriptor_fingerprint",
                                  self.__descriptor_call()),
            params=description.communication.params)
        self.communication.check(self.communication_context)

    def __descriptor_call(self):
        return Expr.maybe_call(self.descriptor_function().name,
                               *self.rack_arguments())

    def host_clock(self, instrument):
        """The clock this instrument exports that the rack itself runs on, or
        None: an instrument whose own domain carries the rack's clock has no
        crossing to make."""
        export = self.description.communication.clock_export
        if export is None:
            return None
        name, _, clock = export.partition(".")
        return clock if name == instrument.name else None

    # Names

    def entity_name(self):
        return self.description.name.entity

    def backplane_name(self):
        return f"{self.entity_name()}{self.BACKPLANE_SUFFIX}"

    def package_name(self):
        return self.description.name.package

    def passthrough(self):
        """Whether the rack hands its APB straight to the instantiating
        design, the transport being the design's own business. A mode with no
        adapter to instantiate is exactly that."""
        return self.communication.UNIT is None

    # Package functions

    def envelope_function(self, name):
        """The envelope of one instrument, as a function of the generics that
        instance takes: whatever a generic dimensions -- a probed bus's width,
        hence a buffer's size, hence the instrument's footprint -- is only
        known once the rack elaborates."""
        contribution = self.instruments[name]
        return FunctionDecl(
            f"{name}_envelope", contribution.generics, "byte_string",
            comment=f"Instrument {name}: what the host enumerates it from, "
                    "and what the rack allocates it from.")

    def envelopes_function(self):
        return FunctionDecl(
            f"{self.entity_name()}_envelopes", self.instrument_generics(),
            "byte_string",
            comment="The envelopes back to back, in description order. CBOR "
                    "items are self-delimiting, so this is all allocation "
                    "needs to walk them.")

    def descriptor_function(self):
        return FunctionDecl(
            f"{self.entity_name()}_descriptor", self.instrument_generics(),
            "byte_string",
            comment="Self-description the host reads from the ROM: every "
                    "instrument, the segment it was allocated and what it "
                    "holds.")

    def apb_config_function(self):
        return FunctionDecl(
            f"{self.entity_name()}_apb_config", self.instrument_generics(),
            self.APB_TYPE, comment=self.__config_comment())

    def instrument_arguments(self, name):
        return tuple(generic.name
                     for generic in self.instruments[name].generics)

    def rack_arguments(self):
        return tuple(generic.name for generic in self.instrument_generics())

    def package_declarations(self):
        declarations = [
            Constant(self.DATA_BUS_WIDTH, "natural",
                     str(self.DATA_BUS_WIDTH_L2),
                     comment="Bytes per APB word, log2."),
            Constant(self.ROM_SIZE, "natural", str(self.ROM_SIZE_L2),
                     comment="Bytes of the descriptor ROM's segment, log2. "
                             "The ROM is pinned at address 0, where the host "
                             "looks for it first on every transport."),
            ]
        for contribution in self.instruments.values():
            declarations += list(contribution.constants)
        declarations += [self.envelope_function(name)
                         for name in self.instruments]
        declarations += [self.envelopes_function(), self.descriptor_function(),
                         self.apb_config_function()]
        for contribution in self.instruments.values():
            declarations += list(contribution.components)
        declarations += [self.backplane_entity().component(),
                         self.entity().component()]
        return tuple(declarations)

    def package_body_declarations(self):
        bodies = [
            FunctionBody(self.envelope_function(name),
                         self.instruments[name].envelope_declarations,
                         self.instruments[name].envelope)
            for name in self.instruments]
        bodies.append(FunctionBody(
            self.envelopes_function(), (),
            Expr.wrapped_join(
                [Expr.maybe_call(f"{name}_envelope",
                                 *self.instrument_arguments(name))
                 for name in self.instruments])))
        bodies.append(FunctionBody(
            self.descriptor_function(),
            (Constant(self.ENVELOPES, "byte_string", self.__envelopes_call()),
             Constant(self.BASES, "base_vector",
                      Expr.call("segment_bases", self.ENVELOPES,
                                self.ROM_SIZE))),
            self.__descriptor()))
        bodies.append(FunctionBody(
            self.apb_config_function(),
            (Constant(self.ENVELOPES, "byte_string", self.__envelopes_call()),),
            Expr.wrapped_call(
                "nsl_amba.apb.config",
                address_width=Expr.call(
                    "nsl_math.arith.max", str(self.ADDRESS_WIDTH),
                    Expr.call("nsl_math.arith.log2",
                              Expr.call("segment_extent", self.ENVELOPES,
                                        self.ROM_SIZE))),
                data_bus_width=f"8 * 2**{self.DATA_BUS_WIDTH}",
                err="true")))
        return tuple(bodies)

    def __envelopes_call(self):
        return Expr.maybe_call(self.envelopes_function().name,
                               *self.rack_arguments())

    def __descriptor(self):
        entries = [
            Expr.wrapped_call("instrument_entry", Expr.index(self.BASES, index),
                              Expr.call("envelope_nth", self.ENVELOPES,
                                        str(index)))
            for index in range(len(self.instruments))]
        body = ",\n".join(Expr.indent(entry) for entry in entries)
        return f"rack_compose(\n{body})"

    def __config_comment(self):
        comment = ("The APB configuration the rack works from: a flat space "
                   "wide enough for the allocated map, and one word per "
                   "register.")
        if self.passthrough():
            comment += (" It is the default of the rack's own generic: an "
                        "instantiating design either takes it as it stands or "
                        "states its own, which the backplane then checks "
                        "against the map.")
        return comment

    def package_file(self):
        return DesignFile(
            header=self.HEADER,
            clauses=DesignFile.context(self.libraries(), self.PACKAGE_USES),
            units=(Package(self.package_name(), self.package_declarations(),
                           comment=self.__package_comment()),
                   PackageBody(self.package_name(),
                               self.package_body_declarations())))

    def __package_comment(self):
        return "\n".join([
            f"Everything {self.entity_name()} and {self.backplane_name()} "
            "have to agree on.",
            "",
            "The address map is allocated out of the very envelopes the "
            "descriptor publishes, by the functions below: an elaboration "
            "constant cannot flow up through an instantiation, so both "
            "entities call these on the generics they were given instead of "
            "one handing the map to the other."])

    # Backplane

    def instrument_ports(self):
        ports = []
        for contribution in self.instruments.values():
            ports += list(contribution.ports)
        return tuple(ports)

    def instrument_generics(self):
        generics = []
        for contribution in self.instruments.values():
            generics += list(contribution.generics)
        return tuple(generics)

    def backplane_entity(self):
        return Entity(
            self.backplane_name(),
            self.instrument_generics() + (self.__apb_config_generic(),),
            (Port(self.CLOCK, "in", "std_ulogic"),
             Port(self.RESET_N, "in", "std_ulogic"),
             Port("apb_i", "in", "nsl_amba.apb.master_t"),
             Port("apb_o", "out", "nsl_amba.apb.slave_t"))
            + self.instrument_ports(),
            comment=self.__backplane_comment())

    def __apb_config_generic(self):
        return Generic(self.APB_CONFIG, self.APB_TYPE,
                       comment="Completer geometry of the whole rack. The "
                               "map below is allocated at elaboration; this "
                               "only has to cover it.")

    def __backplane_comment(self):
        names = ", ".join(self.instruments)
        return "\n".join([
            f"APB backplane of {self.entity_name()}: the descriptor ROM and "
            f"instrument(s) {names}.",
            "",
            "The ROM is pinned at address 0 in its own segment; every "
            "instrument sits in a segment of its own, power-of-two sized and "
            "aligned on its size, so routing to one is a compare of the "
            "address bits above it. An instrument decodes its own low bits "
            "and never learns its base; the descriptor is what tells the host "
            "where each of them sits."])

    def backplane_declarations(self):
        count = len(self.instruments) + 1
        return (
            RawStatement(self.SEGMENT_PREFIX_FUNCTION),
            RawStatement(self.REPORT_FUNCTION),
            Constant(self.ENVELOPES, "byte_string", self.__envelopes_call(),
                     comment="The instruments as the descriptor publishes "
                             "them, which is also what the map is allocated "
                             "from."),
            Constant(self.BASES, "base_vector",
                     Expr.call("segment_bases", self.ENVELOPES, self.ROM_SIZE),
                     comment="Allocated segment base of every instrument, in "
                             "envelope order: ascending by size above the ROM "
                             "segment, each aligned on its own size."),
            Constant(self.ADDRESS_BITS, "natural",
                     Expr.call("nsl_math.arith.log2",
                               Expr.call("segment_extent", self.ENVELOPES,
                                         self.ROM_SIZE)),
                     comment="Address bits the allocated map needs. A "
                             "configuration granting fewer is refused below."),
            Constant(self.DESCRIPTOR, "byte_string",
                     Expr.maybe_call(self.descriptor_function().name,
                                     *self.rack_arguments()),
                     comment="Self-description the host reads from the ROM."),
            Constant(self.FINGERPRINT, "unsigned(31 downto 0)",
                     Expr.call("descriptor_fingerprint", self.DESCRIPTOR),
                     comment="Per-instance UID the host polls to notice the "
                             "gateware changed under it."),
            Constant(self.ALLOCATION, "base_vector",
                     Expr.call("reported", self.ENVELOPES, self.BASES),
                     comment="The allocated map, reported as it is read "
                             "back: one line per instrument in the "
                             "elaboration transcript."),
            Constant(self.ROUTING_TABLE, "nsl_amba.address.address_vector",
                     self.__routing_table(),
                     comment="One prefix per segment: the ROM first, then the "
                             "instruments in envelope order."),
            SignalDecl(self.DOUT,
                       f"nsl_amba.apb.master_vector(0 to {count-1})"),
            SignalDecl(self.DIN, f"nsl_amba.apb.slave_vector(0 to {count-1})"),
            )

    def __routing_table(self):
        width = f"{self.APB_CONFIG}.address_width"
        prefixes = [Expr.wrapped_call("segment_prefix", width, "0",
                                      self.ROM_SIZE)]
        prefixes += [
            Expr.wrapped_call("segment_prefix", width,
                              Expr.index(self.ALLOCATION, index),
                              Expr.call("envelope_size_l2",
                                        Expr.call("envelope_nth",
                                                  self.ENVELOPES, str(index))))
            for index in range(len(self.instruments))]
        arguments = ",\n".join(Expr.indent(prefix) for prefix in prefixes)
        return (f"nsl_amba.address.routing_table({width},\n{arguments})")

    def backplane_checks(self):
        return (
            Check("descriptor_fits_check",
                  "the descriptor must fit the ROM segment",
                  f"{self.DESCRIPTOR}'length <= 2**{self.ROM_SIZE}"),
            Check("address_width_check",
                  "the APB configuration must span the allocated map",
                  f"{self.APB_CONFIG}.address_width >= {self.ADDRESS_BITS}"),
            Check("data_bus_width_check",
                  "the APB configuration must carry the rack's word width",
                  f"{self.APB_CONFIG}.data_bus_width_l2 = "
                  f"{self.DATA_BUS_WIDTH}"),
            )

    def backplane_statements(self):
        statements = []
        for check in self.backplane_checks():
            statements += list(check.statements())
        statements.append(Instance(
            "dispatch", self.DISPATCH,
            generic_map={"config_c": self.APB_CONFIG,
                         "routing_table_c": self.ROUTING_TABLE},
            port_map={"clock_i": self.CLOCK,
                      "reset_n_i": self.RESET_N,
                      "in_i": "apb_i",
                      "in_o": "apb_o",
                      "out_o": self.DOUT,
                      "out_i": self.DIN}))
        statements.append(Instance(
            "descriptor_rom", self.ROM,
            generic_map={"implementation_c": self.ROM_IMPLEMENTATION,
                         "config_c": self.APB_CONFIG,
                         "contents_c": self.DESCRIPTOR},
            port_map={"clock_i": self.CLOCK,
                      "reset_n_i": self.RESET_N,
                      "apb_i": Expr.index(self.DOUT, 0),
                      "apb_o": Expr.index(self.DIN, 0)},
            comment="The descriptor sits at the bottom of the map, where the "
                    "host looks for it first."))
        for contribution in self.instruments.values():
            statements.append(contribution.instance)
        return tuple(statements)

    def backplane_architecture(self):
        return Architecture(self.ARCHITECTURE, self.backplane_name(),
                            self.backplane_declarations(),
                            self.backplane_statements())

    def backplane_file(self):
        return DesignFile(
            header=self.HEADER,
            clauses=DesignFile.context(self.libraries(), self.uses()),
            units=(self.backplane_entity(), self.backplane_architecture()))

    # Rack

    def generics(self):
        generics = list(self.instrument_generics())
        generics += list(self.communication.generics(
            self.communication_context))
        if self.passthrough():
            # Last, so its default may name the instrument generics it is
            # derived from: a generic's default sees the ones declared before
            # it and no others.
            generics.append(Generic(
                self.APB_CONFIG, self.APB_TYPE,
                default=Expr.maybe_call(self.apb_config_function().name,
                                        *self.rack_arguments()),
                comment="Completer geometry the instantiating design drives "
                        "the rack with. The default spans the allocated map; "
                        "a wider one is accepted, a narrower one is refused "
                        "at elaboration."))
        return tuple(generics)

    def ports(self):
        return (tuple(self.clocks.ports) + tuple(self.communication.ports())
                + self.instrument_ports())

    def entity(self):
        return Entity(self.entity_name(), self.generics(), self.ports(),
                      comment=self.__entity_comment())

    def __entity_comment(self):
        names = ", ".join(self.instruments)
        return "\n".join([
            f"Rack holding instrument(s) {names}, reached through "
            f"{self.description.communication.mode}.",
            "",
            "This is the unit a design instantiates: one transport and one "
            "backplane. The backplane holds the descriptor ROM and the "
            "instruments, on a map allocated at elaboration and published by "
            "the descriptor."])

    def rack_declarations(self):
        if self.passthrough():
            return ()
        return (Constant(self.APB_CONFIG, self.APB_TYPE,
                         Expr.maybe_call(self.apb_config_function().name,
                                         *self.rack_arguments()),
                         comment="The transport is internal, so the geometry "
                                 "is the rack's own business."),
                SignalDecl(self.APB_MASTER, "nsl_amba.apb.master_t"),
                SignalDecl(self.APB_SLAVE, "nsl_amba.apb.slave_t"))

    def rack_statements(self):
        if self.passthrough():
            return (self.backplane_instance("apb_i", "apb_o"),)
        return (self.adapter_instance(),
                self.backplane_instance(self.APB_MASTER, self.APB_SLAVE))

    def adapter_instance(self):
        """The library adapter terminating the link, between the rack's
        boundary and the backplane. Its link-side interface is the rack's own,
        bound formal to formal; what is left is the requester geometry and
        whatever the link itself needs."""
        port_map = {self.CLOCK: self.clocks.clock,
                    self.RESET_N: self.clocks.reset_n}
        for port in self.communication.ports():
            port_map[port.name] = port.name
        port_map["apb_o"] = self.APB_MASTER
        port_map["apb_i"] = self.APB_SLAVE
        return Instance(
            "adapter", self.communication.UNIT,
            generic_map=self.communication.generic_map(
                self.communication_context),
            port_map=port_map)

    def backplane_instance(self, master, slave):
        generic_map = {}
        for generic in self.instrument_generics():
            generic_map[generic.name] = generic.name
        generic_map[self.APB_CONFIG] = self.APB_CONFIG
        port_map = {self.CLOCK: self.clocks.clock,
                    self.RESET_N: self.clocks.reset_n,
                    "apb_i": master,
                    "apb_o": slave}
        for port in self.instrument_ports():
            port_map[port.name] = port.name
        return Instance("backplane", self.backplane_name(),
                        generic_map=generic_map, port_map=port_map,
                        comment="Every instrument port crosses untouched, "
                                "clocks included: a clock re-driven through a "
                                "signal assignment would gain a delta cycle "
                                "and skew its domain.")

    def rack_architecture(self):
        return Architecture(self.ARCHITECTURE, self.entity_name(),
                            self.rack_declarations(), self.rack_statements())

    def rack_file(self):
        return DesignFile(
            header=self.HEADER,
            clauses=DesignFile.context(self.libraries(), self.uses()),
            units=(self.entity(), self.rack_architecture()))

    # Files

    def deps(self):
        return tuple(list(self.description.deps())
                     + list(self.communication.deps()) + list(self.DEPS))

    def libraries(self):
        return DesignFile.libraries_of(sorted(set(self.deps())))

    def uses(self):
        return (f"work.{self.package_name()}.all",) + self.PACKAGE_USES

    def plugin_files(self):
        """What the instruments write next to the rack, in description
        order."""
        files = {}
        for contribution in self.instruments.values():
            files.update(contribution.files)
        return files

    def file_names(self):
        """Every VHDL file of the rack, in analysis order."""
        return tuple(
            [name for name in self.plugin_files() if name.endswith(".vhd")]
            + [f"{self.package_name()}.pkg.vhd",
               f"{self.backplane_name()}.vhd",
               f"{self.entity_name()}.vhd"])

    def manifest(self):
        return GbsManifest.of(self.file_names(), self.deps())

    def files(self):
        """File name -> contents, in analysis order."""
        files = dict(self.plugin_files())
        files[f"{self.package_name()}.pkg.vhd"] = self.package_file().render()
        files[f"{self.backplane_name()}.vhd"] = self.backplane_file().render()
        files[f"{self.entity_name()}.vhd"] = self.rack_file().render()
        files[f"{self.package_name()}.gbs.yaml"] = self.manifest().render()
        return files

    def write(self, directory):
        """Write the rack into ``directory``, creating it if needed, and
        return the paths written."""
        os.makedirs(directory, exist_ok=True)
        written = []
        for name, contents in self.files().items():
            path = os.path.join(directory, name)
            with open(path, "w") as f:
                f.write(contents)
            written.append(path)
        return tuple(written)

    SEGMENT_PREFIX_FUNCTION = """\
-- A `width`-bit routing prefix matching one size-aligned segment: the
-- address bits above `size_l2` are the base's own, the ones below are
-- don't-care.
function segment_prefix(width, base, size_l2 : natural) return string is
  variable s : string(1 to width);
  variable rest : natural := base / 2**size_l2;
begin
  s := (others => '-');
  for i in width - size_l2 downto 1 loop
    s(i) := character'val(character'pos('0') + rest mod 2);
    rest := rest / 2;
  end loop;
  return s;
end function;"""

    REPORT_FUNCTION = """\
-- The bases it is given, echoed one instrument per line. Reporting from an
-- elaboration-time function puts the map in a simulation transcript and in a
-- synthesis log alike, and reporting what the router is about to use keeps it
-- from drifting from what is really wired.
function reported(envelopes : byte_string; bases : base_vector)
  return base_vector is
begin
  for i in bases'range loop
    report "rack segment " & envelope_name(envelope_nth(envelopes, i))
      & ": base " & integer'image(bases(i))
      & ", size " & integer'image(2**envelope_size_l2(
        envelope_nth(envelopes, i))) & " bytes"
      severity note;
  end loop;
  return bases;
end function;"""
