"""The ``!bus-explorer`` instrument: an APB master driven from the host.

One instance is one entity behind one APB port, holding the two halves of
``gatecap.bus_explorer`` and the crossings between them: the register shell on
the host clock, where the command engine and the scanner live, and the bus core
on the target's own clock, where a single APB master executes one transaction
at a time. The split is what lets the host explore a register map whose clock
is not the rack's -- a transceiver DRP port, a PLL reconfiguration interface.

The description says how wide the target bus is, how many scan slots the
scanner sweeps and what the map is called; everything else follows. The
footprint is the register-map convention itself, so it is the same 0x400 bytes
for every explorer, whatever its dimensions.

The instance name prefixes every boundary port, and the entity the plugin emits
is named after the rack and the instance, so the backplane binds it formal to
formal.
"""

from __future__ import annotations

from acrobe_plugin.gatecap.generator import (Architecture, Check, ClockDomain,
                                             Constant, DescriptionError,
                                             DesignFile, Entity, Expr, Field,
                                             Generic, Instance,
                                             InstrumentPlugin,
                                             InstrumentRegistry, Port,
                                             SignalDecl)
from .cdc import Stream, StreamCdc


class Explorer:
    """One elaborated instance: its ports, its two halves, the crossings
    between them and the descriptor envelope that publishes the lot."""

    ARCHITECTURE = "rtl"
    HEADER = ("Bus explorer generated by acrobe gatecap generate.\n"
              "Regenerate from the description; edits here are lost.")
    CLOCK = "clock_i"
    RESET_N = "reset_n_i"
    APB_CONFIG = "apb_config_c"
    SIZE_L2 = "size_l2_c"
    FINGERPRINT = "fingerprint_c"
    MAP_SIZE_L2 = "map_size_l2_c"
    ADDRESS_WIDTH = "target_address_width_c"
    DATA_WIDTH = "target_data_width_c"
    SLOT_COUNT = "slot_count_c"
    TIMEOUT = "timeout_c"
    COMMAND_WIDTH = "command_width_c"
    RESPONSE_WIDTH = "response_width_c"
    SHELL = "gatecap.bus_explorer.bus_explorer_shell"
    CORE = "gatecap.bus_explorer.bus_explorer_core"
    ENVELOPE = "gatecap.bus_explorer.bus_explorer_envelope"
    SIZE_FUNCTION = "gatecap.bus_explorer.bus_explorer_size_l2"
    BLOCK_OBJECT = "gatecap.bus_explorer.bus_explorer_block_desc"
    CHILD_MAP = "child_map"
    CHILD_ENTRY = "sibling_entry"
    # The one child of the envelope: the register block, at offset 0.
    BLOCK = "engine"
    HOST = "host"
    TARGET = "target"
    DEPS = ("gatecap.bus_explorer", "gatecap.descriptor", "nsl_amba.apb",
            "nsl_synthesis.assertion")
    USES = ("gatecap.bus_explorer.all",)

    def __init__(self, instrument, host_clock=None):
        self.instrument = instrument
        self.params = instrument.params
        self.host = ClockDomain(self.HOST, self.CLOCK, self.RESET_N)
        self.target_clock = self.__target_domain(host_clock)
        self.down = StreamCdc(self.host, self.target_clock)
        self.up = StreamCdc(self.target_clock, self.host)
        self.__crossings()

    def __target_domain(self, host_clock):
        """The clock the bus core runs on.

        An explorer with no declared clock drives its target bus on the host
        clock, ports and all. One whose declared clock is the very clock the
        rack was told to ride keeps its clock port -- that port is where the
        rack takes the clock from -- and reads it back on the entity's own
        clock input, so the two are one domain and both crossings collapse."""
        if self.clock() is None:
            return self.host
        own = self.clock() != host_clock
        return ClockDomain(self.TARGET,
                           self.clock_port() if own else self.CLOCK,
                           self.reset_port())

    # The description

    def clock(self):
        return self.params["clock"]

    def address_width(self):
        return self.params["address_width"]

    def data_width(self):
        return self.params["data_width"]

    def slots(self):
        return self.params["slots"]

    def timeout(self):
        return self.params["timeout"]

    def map_id(self):
        return self.params["map"]

    def bus_width(self):
        """Bits of the target APB data bus: a data width that is not one of
        the three the bus comes in rides the next one up, as the library's
        target_apb_config computes it."""
        for width in (8, 16, 32):
            if self.data_width() <= width:
                return width
        raise AssertionError(f"data width {self.data_width()} exceeds 32")

    # Names

    def name(self, suffix):
        return f"{self.instrument.name}_{suffix}"

    @staticmethod
    def signal(stem):
        return f"{stem}_s"

    def clock_port(self):
        return self.name(f"{self.clock()}_i")

    def reset_port(self):
        return self.name("reset_n_i")

    def target_port(self, direction):
        return self.name(f"{self.TARGET}_{direction}")

    def entity_name(self, rack_entity):
        return f"{rack_entity}_{self.instrument.name}"

    # Boundary

    def ports(self):
        """What the instance puts on the rack boundary, and what the entity
        takes under the same names: the target bus's clock and reset when it
        has one of its own, then the target APB master pair."""
        ports = []
        if self.clock() is not None:
            ports.append(Port(self.clock_port(), "in", "std_ulogic",
                              comment="Clock the target bus runs on, and the "
                                      "clock of everything the instrument "
                                      "drives onto it."))
            ports.append(Port(self.reset_port(), "in", "std_ulogic"))
        ports.append(Port(
            self.target_port("o"), "out", "nsl_amba.apb.master_t",
            comment=f"Target bus the host explores through this instrument: "
                    f"an APB master of {self.address_width()} address bit(s) "
                    f"and {self.bus_width()} data bits, with ready and err. "
                    f"The addresses the host stages are driven verbatim onto "
                    f"paddr."))
        ports.append(Port(self.target_port("i"), "in", "nsl_amba.apb.slave_t"))
        return tuple(ports)

    def exported_clocks(self):
        """The target bus's clock, under the name the description gave it."""
        if self.clock() is None:
            return {}
        return {self.clock(): self.clock_port()}

    # Geometry

    def constants(self):
        return [
            Constant(self.MAP_SIZE_L2, "natural",
                     Expr.call(self.SIZE_FUNCTION,
                               f"{self.APB_CONFIG}.data_bus_width_l2"),
                     comment="Bytes of address space the register map spans, "
                             "log2: the four regions of the register-map "
                             "convention, one word per register."),
            Constant(self.ADDRESS_WIDTH, "natural",
                     str(self.address_width()),
                     comment="Bits of a target address, as the host stages it "
                             "and as paddr carries it."),
            Constant(self.DATA_WIDTH, "natural", str(self.data_width()),
                     comment=f"Bits of a target data word. The bus itself is "
                             f"{self.bus_width()} bits wide: write data is "
                             f"truncated to the declared width and read data "
                             f"zero-extended from it."),
            Constant(self.SLOT_COUNT, "natural", str(self.slots()),
                     comment="Scan slots the scanner sweeps, hence result "
                             "words in the status region and address words in "
                             "the array region."),
            Constant(self.TIMEOUT, "positive", str(self.timeout()),
                     comment="Host cycles an access may take before the "
                             "engine abandons it and reports a timeout."),
            Constant(self.COMMAND_WIDTH, "natural",
                     Expr.call("command_width", self.ADDRESS_WIDTH,
                               self.DATA_WIDTH),
                     comment="Bits of one packed command and of one packed "
                             "response: what the crossings carry."),
            Constant(self.RESPONSE_WIDTH, "natural",
                     Expr.call("response_width", self.DATA_WIDTH)),
            ]

    def checks(self):
        return [
            Check("footprint_check",
                  "the declared footprint must match the map the bus explorer "
                  "decodes",
                  f"{self.SIZE_L2} = {self.MAP_SIZE_L2}"),
            Check("address_width_check",
                  "the APB configuration must cover the bus explorer's "
                  "footprint",
                  f"{self.APB_CONFIG}.address_width >= {self.MAP_SIZE_L2}"),
            ]

    # Structure

    def command(self, side):
        return Stream(self.signal(f"{side}_command"),
                      self.signal(f"{side}_command_valid"),
                      self.signal(f"{side}_command_ready"))

    def response(self, side):
        return Stream(self.signal(f"{side}_response"),
                      self.signal(f"{side}_response_valid"),
                      self.signal(f"{side}_response_ready"))

    def signals(self):
        signals = []
        for side in ("shell", "core"):
            command = self.command(side)
            signals.append(SignalDecl(
                command.data,
                f"std_ulogic_vector({self.COMMAND_WIDTH}-1 downto 0)"))
            signals.append(SignalDecl(command.valid, "std_ulogic"))
            signals.append(SignalDecl(command.ready, "std_ulogic"))
        for side in ("core", "shell"):
            response = self.response(side)
            signals.append(SignalDecl(
                response.data,
                f"std_ulogic_vector({self.RESPONSE_WIDTH}-1 downto 0)"))
            signals.append(SignalDecl(response.valid, "std_ulogic"))
            signals.append(SignalDecl(response.ready, "std_ulogic"))
        return signals

    def __crossings(self):
        """The inner contract, crossed: one stream per direction."""
        self.down.stream("command", self.COMMAND_WIDTH,
                         self.command("shell"), self.command("core"),
                         self.host.reset_n)
        self.up.stream("response", self.RESPONSE_WIDTH,
                       self.response("core"), self.response("shell"),
                       self.host.reset_n)

    def shell(self):
        command = self.command("shell")
        response = self.response("shell")
        return Instance(
            "shell", self.SHELL,
            generic_map={
                "apb_config_c": self.APB_CONFIG,
                self.ADDRESS_WIDTH: self.ADDRESS_WIDTH,
                self.DATA_WIDTH: self.DATA_WIDTH,
                self.SLOT_COUNT: self.SLOT_COUNT,
                self.TIMEOUT: self.TIMEOUT,
                "fingerprint_c": self.FINGERPRINT,
                },
            port_map={
                "clock_i": self.host.clock,
                "reset_n_i": self.host.reset_n,
                "apb_i": "apb_i",
                "apb_o": "apb_o",
                "command_o": command.data,
                "command_valid_o": command.valid,
                "command_ready_i": command.ready,
                "response_i": response.data,
                "response_valid_i": response.valid,
                "response_ready_o": response.ready,
                },
            comment="The register file, the command engine, the scanner and "
                    "the timeout, on the host clock. Nothing here needs its "
                    "clock to run between accesses.")

    def core(self):
        command = self.command("core")
        response = self.response("core")
        return Instance(
            "core", self.CORE,
            generic_map={
                self.ADDRESS_WIDTH: self.ADDRESS_WIDTH,
                self.DATA_WIDTH: self.DATA_WIDTH,
                },
            port_map={
                "clock_i": self.target_clock.clock,
                "reset_n_i": self.target_clock.reset_n,
                "command_i": command.data,
                "command_valid_i": command.valid,
                "command_ready_o": command.ready,
                "response_o": response.data,
                "response_valid_o": response.valid,
                "response_ready_i": response.ready,
                "apb_o": self.target_port("o"),
                "apb_i": self.target_port("i"),
                },
            comment="One APB master, on the target's clock, executing one "
                    "transaction at a time. It owns no timeout: an access the "
                    "target never answers stays outstanding here long after "
                    "the shell has given up on it.")

    # Entity

    def entity(self, rack_entity):
        return Entity(
            self.entity_name(rack_entity),
            (Generic(self.APB_CONFIG, "nsl_amba.apb.config_t",
                     comment="Completer geometry of the rack this instrument "
                             "sits in. Only its low bits are decoded here."),
             Generic(self.SIZE_L2, "natural",
                     comment="Address-space footprint the envelope declares, "
                             "log2. The map below is fixed by the "
                             "register-map convention and asserted equal to "
                             "it."),
             Generic(self.FINGERPRINT, "unsigned(31 downto 0)",
                     comment="Per-instance UID of the rack's descriptor, "
                             "which the register file reports.")),
            (Port(self.CLOCK, "in", "std_ulogic"),
             Port(self.RESET_N, "in", "std_ulogic"),
             Port("apb_i", "in", "nsl_amba.apb.master_t"),
             Port("apb_o", "out", "nsl_amba.apb.slave_t"))
            + self.ports(),
            comment=self.__entity_comment())

    def __entity_comment(self):
        lines = [f"Bus explorer {self.instrument.name}: an APB master the "
                 f"host drives, on {self.address_width()} address bit(s) and "
                 f"{self.data_width()} data bit(s), with {self.slots()} scan "
                 f"slot(s).",
                 "",
                 "One APB completer holds the whole instrument: the action, "
                 "config, status and array regions of the register-map "
                 "convention. There is no pass-through aperture -- every "
                 "target access goes through the command engine, which "
                 f"abandons one the target has not answered in "
                 f"{self.timeout()} host cycles."]
        if self.clock() is None:
            lines += ["",
                      "The instrument names no clock of its own, so the "
                      "target bus runs on the host clock and both crossings "
                      "of the inner contract are plain wires."]
        else:
            lines += ["",
                      "The register shell runs on the rack's clock and the "
                      "bus core on the target's own, so the command and "
                      "response streams cross between them."]
        return "\n".join(lines)

    def declarations(self):
        return tuple(self.constants() + self.signals()
                     + self.down.declarations + self.up.declarations)

    def statements(self):
        statements = []
        for check in self.checks():
            statements += list(check.statements())
        statements += [self.shell(), self.core()]
        statements += self.down.statements + self.up.statements
        return tuple(statements)

    def architecture(self, rack_entity):
        return Architecture(self.ARCHITECTURE, self.entity_name(rack_entity),
                            self.declarations(), self.statements())

    def file(self, rack_entity):
        return DesignFile(
            header=self.HEADER,
            clauses=DesignFile.context(
                DesignFile.libraries_of(sorted(set(self.deps()))), self.USES),
            units=(self.entity(rack_entity),
                   self.architecture(rack_entity))).render()

    # Descriptor

    def envelope(self, data_bus_width_l2):
        return Expr.wrapped_call(
            self.ENVELOPE,
            size_l2=Expr.call(self.SIZE_FUNCTION, data_bus_width_l2),
            name=Expr.string(self.instrument.name),
            children=self.children(),
            address_width=str(self.address_width()),
            data_width=str(self.data_width()),
            slot_count=str(self.slots()),
            map_id=Expr.string(self.map_id()))

    def children(self):
        entry = Expr.wrapped_call(self.CHILD_ENTRY, Expr.string(self.BLOCK),
                                  "0", Expr.maybe_call(self.BLOCK_OBJECT))
        return f"{self.CHILD_MAP}(\n{Expr.indent(entry)})"

    # Dependencies

    def deps(self):
        return tuple(list(self.DEPS) + list(self.down.deps())
                     + list(self.up.deps()))


@InstrumentRegistry.register
class BusExplorer(InstrumentPlugin):
    """A bus master the host drives: staged operations on a target register
    map, and a scanner keeping the registers of interest live in the status
    poll."""

    TAG = "!bus-explorer"
    KEYS = ("clock", "address-width", "data-width", "slots", "map", "timeout")

    # Bounds the library entities declare on their own generics, caught here
    # instead, where the description can still be pointed at.
    WIDTH_MAX = 32
    SLOTS_MAX = 32
    # Slots cost a result word each and nothing else; eight is what the
    # library defaults to.
    SLOTS_DEFAULT = 8
    # Host cycles: generous enough that only a target that never answers ever
    # reaches it.
    TIMEOUT_DEFAULT = 65536
    MAP_DEFAULT = ""

    @classmethod
    def parse(cls, payload, path):
        clock = Field.string(payload, "clock", path)
        if clock is not None:
            cls.__clock(clock, f"{path}.clock")
        return {
            "clock": clock,
            "address_width": cls.__width(payload, "address-width", path),
            "data_width": cls.__width(payload, "data-width", path),
            "slots": Field.integer(payload, "slots", path,
                                   default=cls.SLOTS_DEFAULT, minimum=1,
                                   maximum=cls.SLOTS_MAX),
            "map": cls.__map(payload, path),
            "timeout": Field.integer(payload, "timeout", path,
                                     default=cls.TIMEOUT_DEFAULT, minimum=1),
            }

    @staticmethod
    def __clock(clock, path):
        """The clock the target bus runs on, named the way a capture domain
        names its own: one identifier, which becomes a boundary port of the
        instance and the clock the rack may be told to ride as
        ``<instance>.<clock>``."""
        if "." in clock:
            raise DescriptionError(
                f"clock {clock!r} must be a plain name: a bus explorer "
                "declares a clock of its own, which the instance exports as "
                "<instance>.<clock>", path)
        Field.identifier(clock, path, "clock name")

    @classmethod
    def __width(cls, payload, key, path):
        """A target dimension. Neither has a sane default -- an explorer of
        the wrong width explores nothing -- so the description states both."""
        width = Field.integer(payload, key, path, minimum=1,
                              maximum=cls.WIDTH_MAX)
        if width is None:
            raise DescriptionError(f"{key} is required", path)
        return width

    @classmethod
    def __map(cls, payload, path):
        """The identifier of the target's register map: free text the host
        resolves against its own library of SVD documents, and which rides the
        descriptor verbatim."""
        text = Field.string(payload, "map", path, default=cls.MAP_DEFAULT)
        for c in text:
            if not c.isprintable() or not c.isascii():
                raise DescriptionError(
                    f"map {text!r} must be printable ASCII: it rides the "
                    f"descriptor as a text, {c!r} does not", f"{path}.map")
        return text

    # Contributions

    @classmethod
    def explorer(cls, instrument, host_clock=None):
        return Explorer(instrument, host_clock)

    @classmethod
    def contributed(cls, context):
        return Explorer(context.instrument, context.host_clock)

    @classmethod
    def ports(cls, instrument):
        return cls.explorer(instrument).ports()

    @classmethod
    def clocks(cls, instrument):
        return cls.explorer(instrument).exported_clocks()

    @classmethod
    def envelope(cls, context):
        return cls.contributed(context).envelope(context.data_bus_width_l2)

    @classmethod
    def components(cls, context):
        explorer = cls.contributed(context)
        return (explorer.entity(context.entity).component(),)

    @classmethod
    def instance(cls, context):
        explorer = cls.contributed(context)
        port_map = {Explorer.CLOCK: context.clock,
                    Explorer.RESET_N: context.reset_n,
                    "apb_i": context.apb_master,
                    "apb_o": context.apb_slave}
        for port in explorer.ports():
            port_map[port.name] = port.name
        return Instance(
            context.instrument.label("explorer"),
            explorer.entity_name(context.entity),
            generic_map={Explorer.APB_CONFIG: context.apb_config,
                         Explorer.SIZE_L2: context.size_l2,
                         Explorer.FINGERPRINT: context.fingerprint},
            port_map=port_map,
            comment=f"Bus explorer {context.instrument.name}. Every port "
                    "crosses untouched, the target's clock included: a clock "
                    "re-driven through a signal assignment would gain a delta "
                    "cycle and skew its domain.")

    @classmethod
    def files(cls, context):
        explorer = cls.contributed(context)
        name = explorer.entity_name(context.entity)
        return {f"{name}.vhd": explorer.file(context.entity)}

    @classmethod
    def deps(cls, instrument):
        return cls.explorer(instrument).deps()
