"""The ``!logic-analyzer`` instrument: gatecap's capture machinery as a plugin.

One instance is one entity behind one APB port, holding every capture domain
of one correlated group: their probe vectors, capture cores, trace buffers,
control blocks and triggers, the crossings between the register clock and each
capture clock, and the cross-domain glue -- the ready rendezvous that keeps a
shared trigger disabled until every subscriber holds its pre-trigger context,
and the fan-out of its tick back to them.

Everything the description says about capture lives in the instrument's body:
the ``storage``, ``capture`` and ``trigger`` dimensioning defaults, and the
``domains`` each with its clock, its rate, its own overrides and its signals.

The instance name prefixes every boundary port and generic, so two analyzers
in one rack coexist with domains of the same name. The entity the plugin emits
is named after the rack and the instance, and carries those very names, so the
backplane binds it formal to formal.

The map behind the APB port is the analyzer's own (see :mod:`.layout`), and so
is its footprint: the envelope declares it, the backplane allocates from it,
and the entity recomputes it and asserts the two agree.

Importing this package also registers the probe types a description may name
(:mod:`.signal_types`): they are this instrument's vocabulary and nothing
else's.
"""

from __future__ import annotations

from acrobe_plugin.gatecap.generator import (Architecture, ClockDomain,
                                             Constant, DesignFile, Entity,
                                             Expr, Generic, Instance,
                                             InstrumentPlugin,
                                             InstrumentRegistry, Port,
                                             RawStatement, SignalDecl)
from . import signal_types  # noqa: F401 -- registers the stock probe types
from .clusters import DomainCluster
from .layout import BlockLayout
from .parser import BodyParser
from .topology import TriggerTopology


class Clocks:
    """Which clock every part of an analyzer runs on: the register side on the
    instrument's own clock port, each domain on its own.

    ``host_clock`` names the domain whose clock the rack itself runs on, if
    any: the rack takes it from that domain's port and hands it back as the
    instrument's clock, so the two are one clock and every crossing between
    them collapses to a wire. The domain keeps its own reset, exactly as an
    asynchronous one does."""

    HOST = "host"

    def __init__(self, clock, reset_n, domains, host_clock=None):
        self.host = ClockDomain(self.HOST, clock, reset_n)
        self.domains = {}
        for domain in domains:
            own = domain.name != host_clock
            self.domains[domain.name] = ClockDomain(
                domain.name, domain.clock_port() if own else clock,
                domain.reset_port())

    def of(self, name):
        return self.domains[name]


class Analyzer:
    """One elaborated instance: its domains, blocks, crossings and the two
    artefacts they feed -- the instrument entity and its descriptor
    envelope."""

    ARCHITECTURE = "rtl"
    HEADER = ("Logic analyzer generated by acrobe gatecap generate.\n"
              "Regenerate from the description; edits here are lost.")
    CLOCK = "clock_i"
    RESET_N = "reset_n_i"
    APB_CONFIG = "apb_config_c"
    SIZE_L2 = "size_l2_c"
    FINGERPRINT = "fingerprint_c"
    DATA_BUS_WIDTH = "data_bus_width_l2_c"
    DISPATCH = "nsl_amba.apb_routing.apb_dispatch"
    ENVELOPE = "logic_analyzer_envelope"
    CHILD_MAP = "child_map"
    CHILD_ENTRY = "sibling_entry"
    DEPS = ("gatecap.descriptor",)

    def __init__(self, instrument, host_clock=None):
        self.instrument = instrument
        self.host_clock = host_clock
        self.domains = tuple(domain.scoped(instrument.name)
                             for domain in instrument.params["domains"])
        self.clocks = Clocks(self.CLOCK, self.RESET_N, self.domains,
                             host_clock)
        self.layout = BlockLayout(self.domains, instrument.path())
        self.topology = TriggerTopology(self.domains, self.clocks, self.layout)
        self.clusters = {}
        for domain in self.domains:
            if not domain.captures():
                continue
            self.clusters[domain.name] = DomainCluster.of(
                domain, self.clocks.host, self.clocks.of(domain.name),
                self.topology.source(domain.name),
                self.layout.of(domain.name))

    # Boundary

    def ports(self):
        """What the instance puts on the rack boundary, and what the entity
        takes under the same names: one clock and reset per domain, then the
        probes.

        A domain whose clock the rack runs on keeps its clock port -- that
        port is where the rack takes the clock from -- and the entity reads
        that same clock back on its own clock input."""
        ports = []
        for domain in self.domains:
            ports.append(Port(domain.clock_port(), "in", "std_ulogic"))
            ports.append(Port(domain.reset_port(), "in", "std_ulogic"))
            for probe in domain.probes:
                ports += list(probe.plugin.ports(probe))
        return tuple(ports)

    def generics(self):
        generics = []
        for domain in self.domains:
            for probe in domain.probes:
                generics += list(probe.plugin.generics(probe))
        return tuple(generics)

    def exported_clocks(self):
        """Every domain's clock, under the domain's own name."""
        return {domain.name: domain.clock_port() for domain in self.domains}

    def exported_clock_rates(self):
        """The rate of every domain that states one."""
        return {domain.name: domain.frequency for domain in self.domains
                if domain.frequency}

    # Geometry

    def geometry(self):
        """The elaboration-time constants the entity and the envelope are both
        built from, in dependency order. Emitted into the entity's declarative
        part and into the envelope function alike, so the map the analyzer
        decodes and the map it publishes cannot drift apart."""
        declarations = [
            Constant("word_bytes_c", "natural", f"2**{self.DATA_BUS_WIDTH}"),
            Constant("word_bits_c", "natural", "8 * word_bytes_c"),
            ]
        declarations += self.topology.constants()
        for cluster in self.clusters.values():
            declarations += cluster.geometry()
        declarations += self.layout.declarations(
            [cluster.buffer_size_l2() for cluster in self.clusters.values()])
        return declarations

    def offsets(self):
        """Where each block sits inside the analyzer's segment. Only the
        descriptor needs them: a block decodes its own low bits and never
        learns its base."""
        return self.layout.offsets()

    # Descriptor

    def envelope(self):
        return Expr.wrapped_call(
            self.ENVELOPE,
            size_l2=self.layout.MAP_SIZE_L2,
            name=Expr.string(self.instrument.name),
            children=self.children(),
            control_names=Expr.string(",".join(self.control_names())))

    def control_names(self):
        """The children-map names of the capture controls one arm covers, in
        domain order: what makes the domains of this analyzer one correlated
        group."""
        return [cluster.regions.control.key
                for cluster in self.clusters.values()]

    def children(self):
        entries = []
        for domain in self.domains:
            cluster = self.clusters.get(domain.name)
            if cluster is not None:
                entries.append(self.__child(cluster.regions.buffer,
                                            cluster.buffer_object()))
                entries.append(self.__child(cluster.regions.control,
                                            cluster.control_object()))
            host = self.topology.hosts.get(domain.name)
            if host is not None:
                entries.append(self.__child(host.block,
                                            host.descriptor_object()))
        body = ",\n".join(Expr.indent(entry) for entry in entries)
        return f"{self.CHILD_MAP}(\n{body})"

    def __child(self, block, obj):
        return Expr.wrapped_call(self.CHILD_ENTRY, Expr.string(block.key),
                                 block.offset(), obj)

    # Entity

    def entity_name(self, rack_entity):
        return f"{rack_entity}_{self.instrument.name}"

    def entity(self, rack_entity):
        return Entity(
            self.entity_name(rack_entity),
            (Generic(self.APB_CONFIG, "nsl_amba.apb.config_t",
                     comment="Completer geometry of the rack this analyzer "
                             "sits in. Only its low bits are decoded here."),
             Generic(self.SIZE_L2, "natural",
                     comment="Address-space footprint the envelope declares, "
                             "log2. The map below is laid out independently "
                             "and asserted equal to it."),
             Generic(self.FINGERPRINT, "unsigned(31 downto 0)",
                     comment="Per-instance UID of the rack's descriptor, "
                             "which every control block reports."))
            + self.generics(),
            (Port(self.CLOCK, "in", "std_ulogic"),
             Port(self.RESET_N, "in", "std_ulogic"),
             Port("apb_i", "in", "nsl_amba.apb.master_t"),
             Port("apb_o", "out", "nsl_amba.apb.slave_t"))
            + self.ports(),
            comment=self.__entity_comment())

    def __entity_comment(self):
        names = ", ".join(domain.name for domain in self.domains)
        lines = [f"Logic analyzer {self.instrument.name}: capture domain(s) "
                 f"{names}.",
                 "",
                 "One APB completer holds every block: one power-of-two "
                 "region per control,",
                 "trace buffer and trigger, selected by the address bits just "
                 "below the",
                 "footprint. A block decodes only its low address bits, so it "
                 "is oblivious to",
                 "its base; the descriptor tells the host where each of them "
                 "sits."]
        if len(self.clusters) > 1:
            lines += ["",
                      "The domains are one correlated group: the hosting "
                      "trigger stays disabled",
                      "until every capture holds its pre-trigger context, and "
                      "its tick reaches",
                      "them all."]
        return "\n".join(lines)

    def declarations(self):
        declarations = [
            RawStatement(BlockLayout.PREFIX_FUNCTION),
            Constant(self.DATA_BUS_WIDTH, "natural",
                     f"{self.APB_CONFIG}.data_bus_width_l2",
                     comment="Bytes per APB word, log2, as the rack granted "
                             "it."),
            ]
        declarations += self.geometry()
        declarations.append(self.layout.routing_table())
        for cluster in self.clusters.values():
            declarations += cluster.signals()
            declarations += cluster.down.declarations + cluster.up.declarations
        declarations += self.topology.declarations()
        declarations += [
            SignalDecl("dout_s", "nsl_amba.apb.master_vector"
                       f"(0 to {self.layout.count()-1})"),
            SignalDecl("din_s", "nsl_amba.apb.slave_vector"
                       f"(0 to {self.layout.count()-1})"),
            ]
        return tuple(declarations)

    def checks(self):
        checks = list(self.layout.checks()) + self.topology.checks()
        for cluster in self.clusters.values():
            checks += cluster.checks()
        return checks

    def statements(self):
        statements = []
        for check in self.checks():
            statements += list(check.statements())
        statements.append(Instance(
            "dispatch", self.DISPATCH,
            generic_map={"config_c": self.APB_CONFIG,
                         "routing_table_c": self.layout.ROUTING_TABLE},
            port_map={"clock_i": self.CLOCK,
                      "reset_n_i": self.RESET_N,
                      "in_i": "apb_i",
                      "in_o": "apb_o",
                      "out_o": "dout_s",
                      "out_i": "din_s"}))
        for cluster in self.clusters.values():
            statements += cluster.statements()
        statements += self.topology.statements()
        return tuple(statements)

    def architecture(self, rack_entity):
        return Architecture(self.ARCHITECTURE, self.entity_name(rack_entity),
                            self.declarations(), self.statements())

    def file(self, rack_entity):
        return DesignFile(
            header=self.HEADER,
            clauses=DesignFile.context(
                DesignFile.libraries_of(sorted(set(self.deps())))),
            units=(self.entity(rack_entity),
                   self.architecture(rack_entity))).render()

    # Dependencies

    def deps(self):
        deps = list(self.DEPS) + list(BlockLayout.DEPS)
        for domain in self.domains:
            for probe in domain.probes:
                deps += list(probe.plugin.deps(probe))
        for cluster in self.clusters.values():
            deps += list(cluster.deps())
        deps += list(self.topology.deps())
        return tuple(deps)


@InstrumentRegistry.register
class LogicAnalyzer(InstrumentPlugin):
    """gatecap's capture machinery: one or several capture domains, one
    correlated arm group, one entity."""

    TAG = "!logic-analyzer"
    KEYS = BodyParser.KEYS

    @classmethod
    def parse(cls, payload, path):
        return BodyParser.parse(payload, path)

    @classmethod
    def analyzer(cls, instrument, host_clock=None):
        return Analyzer(instrument, host_clock)

    @classmethod
    def contributed(cls, context):
        return Analyzer(context.instrument, context.host_clock)

    @classmethod
    def ports(cls, instrument):
        return cls.analyzer(instrument).ports()

    @classmethod
    def generics(cls, instrument):
        return cls.analyzer(instrument).generics()

    @classmethod
    def clocks(cls, instrument):
        return cls.analyzer(instrument).exported_clocks()

    @classmethod
    def clock_rates(cls, instrument):
        return cls.analyzer(instrument).exported_clock_rates()

    @classmethod
    def envelope(cls, context):
        return cls.contributed(context).envelope()

    @classmethod
    def envelope_declarations(cls, context):
        analyzer = cls.contributed(context)
        return tuple(analyzer.geometry() + analyzer.offsets())

    @classmethod
    def components(cls, context):
        analyzer = cls.contributed(context)
        return (analyzer.entity(context.entity).component(),)

    @classmethod
    def instance(cls, context):
        instrument = context.instrument
        analyzer = cls.contributed(context)
        generic_map = {Analyzer.APB_CONFIG: context.apb_config,
                       Analyzer.SIZE_L2: context.size_l2,
                       Analyzer.FINGERPRINT: context.fingerprint}
        for generic in analyzer.generics():
            generic_map[generic.name] = generic.name
        port_map = {Analyzer.CLOCK: context.clock,
                    Analyzer.RESET_N: context.reset_n,
                    "apb_i": context.apb_master,
                    "apb_o": context.apb_slave}
        for port in analyzer.ports():
            port_map[port.name] = port.name
        return Instance(
            instrument.label("analyzer"), analyzer.entity_name(context.entity),
            generic_map=generic_map, port_map=port_map,
            comment=f"Logic analyzer {instrument.name}: "
                    f"{len(analyzer.domains)} capture domain(s). Every port "
                    "crosses untouched, clocks included: a clock re-driven "
                    "through a signal assignment would gain a delta cycle and "
                    "skew its domain.")

    @classmethod
    def files(cls, context):
        analyzer = cls.contributed(context)
        name = analyzer.entity_name(context.entity)
        return {f"{name}.vhd": analyzer.file(context.entity)}

    @classmethod
    def deps(cls, instrument):
        return cls.analyzer(instrument).deps()
